# Generated by Django 3.0.4 on 2020-03-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('phone', models.IntegerField(max_length=20)),
            ],
        ),
    ]
