# Generated by Django 3.0.4 on 2020-03-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_username', models.CharField(max_length=50)),
                ('dish_name', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('v_or_n', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='outlet',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
