# Generated by Django 3.0.4 on 2020-03-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200320_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
